name: Hello

on:
  push:
    branches:
      - master

jobs:
  hello_wolrd:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "hola"
      - name: Give me date
        run: date
      - run: |
          ls -1